export interface KwcagItem {
  readonly id: string;
  readonly name: string;
  readonly nameEn: string;
  readonly principle: number;
  readonly principleName: string;
  readonly level: string;
  readonly auto: boolean | "partial";
  readonly axeRules: readonly string[];
  readonly customRule?: string;
  readonly description: string;
}

export const KWCAG_ITEMS: readonly KwcagItem[] = [
  // Principle 1: Perceivable
  {
    id: "5.1.1",
    name: "적절한 대체 텍스트 제공",
    nameEn: "Appropriate alternative text",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: true,
    axeRules: [
      "image-alt",
      "input-image-alt",
      "area-alt",
      "object-alt",
      "svg-img-alt",
      "role-img-alt",
    ],
    description: "텍스트 아닌 콘텐츠에는 적절한 대체 텍스트를 제공해야 한다.",
  },
  {
    id: "5.2.1",
    name: "자막 제공",
    nameEn: "Captions provided",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["video-caption", "audio-caption"],
    description: "멀티미디어 콘텐츠에는 자막, 대본 또는 수어를 제공해야 한다.",
  },
  {
    id: "5.3.1",
    name: "표의 구성",
    nameEn: "Table structure",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: true,
    axeRules: [
      "td-headers-attr",
      "th-has-data-cells",
      "table-fake-caption",
    ],
    customRule: "table-structure",
    description: "이해하기 쉽게 구성해야 한다.",
  },
  {
    id: "5.3.2",
    name: "콘텐츠의 선형구조",
    nameEn: "Linear content structure",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["presentation-role-conflict"],
    description: "콘텐츠는 논리적인 순서로 제공해야 한다.",
  },
  {
    id: "5.3.3",
    name: "명확한 지시사항 제공",
    nameEn: "Clear instructions",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: "partial",
    axeRules: [],
    customRule: "sensory-instructions",
    description: "지시사항은 모양, 크기, 위치, 방향, 색, 소리 등에 관계없이 인식될 수 있어야 한다.",
  },
  {
    id: "5.4.1",
    name: "색에 무관한 콘텐츠 인식",
    nameEn: "Content recognition regardless of color",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["link-in-text-block"],
    description: "콘텐츠는 색에 관계없이 인식될 수 있어야 한다.",
  },
  {
    id: "5.4.2",
    name: "자동 재생 금지",
    nameEn: "No auto-play",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: true,
    axeRules: ["no-autoplay-audio"],
    customRule: "auto-play",
    description: "자동으로 소리가 재생되지 않아야 한다.",
  },
  {
    id: "5.4.3",
    name: "텍스트 콘텐츠의 명도 대비",
    nameEn: "Text contrast ratio",
    principle: 1,
    principleName: "인식의 용이성",
    level: "AA",
    auto: true,
    axeRules: ["color-contrast", "color-contrast-enhanced"],
    description: "텍스트 콘텐츠와 배경 간의 명도 대비는 4.5대 1 이상이어야 한다.",
  },
  {
    id: "5.4.4",
    name: "콘텐츠 간의 구분",
    nameEn: "Content distinction",
    principle: 1,
    principleName: "인식의 용이성",
    level: "A",
    auto: "partial",
    axeRules: [],
    customRule: "content-distinction",
    description: "이웃한 콘텐츠는 구별될 수 있어야 한다.",
  },

  // Principle 2: Operable
  {
    id: "6.1.1",
    name: "키보드 사용 보장",
    nameEn: "Keyboard accessibility",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: true,
    axeRules: [
      "keyboard-focusable-content",
      "scrollable-region-focusable",
      "interactive-supports-focus",
      "no-noninteractive-tabindex",
    ],
    description: "모든 기능은 키보드만으로도 사용할 수 있어야 한다.",
  },
  {
    id: "6.1.2",
    name: "초점 이동과 표시",
    nameEn: "Focus movement and visibility",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: true,
    axeRules: ["focus-order-semantics", "tabindex"],
    customRule: "focus-visible",
    description: "키보드에 의한 초점은 논리적으로 이동해야 하며 시각적으로 구별할 수 있어야 한다.",
  },
  {
    id: "6.1.3",
    name: "조작 가능",
    nameEn: "Operable controls",
    principle: 2,
    principleName: "운용의 용이성",
    level: "AA",
    auto: true,
    axeRules: ["target-size"],
    description: "사용자 입력 및 컨트롤은 조작 가능하도록 제공되어야 한다.",
  },
  {
    id: "6.1.4",
    name: "문자 단축키",
    nameEn: "Character key shortcuts",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["accesskeys"],
    description: "문자 단축키는 오동작으로 인한 오류를 방지하여야 한다.",
  },
  {
    id: "6.2.1",
    name: "응답시간 조절",
    nameEn: "Adjustable timing",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["meta-refresh"],
    customRule: "timing-adjustable",
    description: "시간제한이 있는 콘텐츠는 응답시간을 조절할 수 있어야 한다.",
  },
  {
    id: "6.2.2",
    name: "정지 기능 제공",
    nameEn: "Pause functionality",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["marquee"],
    customRule: "pause-stop",
    description: "자동으로 변경되는 콘텐츠는 움직임을 제어할 수 있어야 한다.",
  },
  {
    id: "6.3.1",
    name: "깜빡임과 번쩍임 사용 제한",
    nameEn: "Flash and blink restriction",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["blink"],
    customRule: "blink-flash",
    description: "초당 3~50회 주기로 깜빡이거나 번쩍이는 콘텐츠를 제공하지 않아야 한다.",
  },
  {
    id: "6.4.1",
    name: "반복 영역 건너뛰기",
    nameEn: "Skip navigation",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: true,
    axeRules: ["bypass", "skip-link"],
    customRule: "skip-nav",
    description: "콘텐츠의 반복되는 영역은 건너뛸 수 있어야 한다.",
  },
  {
    id: "6.4.2",
    name: "제목 제공",
    nameEn: "Page title",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: true,
    axeRules: [
      "document-title",
      "page-has-heading-one",
      "heading-order",
      "empty-heading",
    ],
    customRule: "page-title",
    description: "페이지, 프레임, 콘텐츠 블록에는 적절한 제목을 제공해야 한다.",
  },
  {
    id: "6.4.3",
    name: "적절한 링크 텍스트",
    nameEn: "Appropriate link text",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: true,
    axeRules: ["link-name"],
    customRule: "link-text",
    description: "링크 텍스트는 용도나 목적을 이해할 수 있도록 제공해야 한다.",
  },
  {
    id: "6.4.4",
    name: "고정된 참조 위치 정보",
    nameEn: "Consistent navigation",
    principle: 2,
    principleName: "운용의 용이성",
    level: "AA",
    auto: "partial",
    axeRules: [],
    customRule: "consistent-nav",
    description: "전자출판문서 형식의 웹 페이지는 각 페이지로 이동할 수 있는 기능이 있어야 한다.",
  },
  {
    id: "6.5.1",
    name: "단일 포인터 입력 지원",
    nameEn: "Single pointer input",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: "partial",
    axeRules: [],
    description: "다중 포인터 또는 경로기반 동작은 단일 포인터 입력으로도 조작할 수 있어야 한다.",
  },
  {
    id: "6.5.2",
    name: "포인터 입력 취소",
    nameEn: "Pointer cancellation",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: false,
    axeRules: [],
    description: "포인터의 단일 입력으로 실행되는 기능은 취소할 수 있어야 한다.",
  },
  {
    id: "6.5.3",
    name: "레이블과 네임",
    nameEn: "Label in name",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: true,
    axeRules: ["label-content-name-mismatch"],
    description: "시각적으로 표시되는 텍스트가 네임에 포함되어야 한다.",
  },
  {
    id: "6.5.4",
    name: "동작기반 작동",
    nameEn: "Motion actuation",
    principle: 2,
    principleName: "운용의 용이성",
    level: "A",
    auto: false,
    axeRules: [],
    description: "동작으로 작동하는 기능은 사용자 인터페이스 구성요소로도 조작할 수 있어야 한다.",
  },

  // Principle 3: Understandable
  {
    id: "7.1.1",
    name: "기본 언어 표시",
    nameEn: "Language of page",
    principle: 3,
    principleName: "이해의 용이성",
    level: "A",
    auto: true,
    axeRules: ["html-has-lang", "html-lang-valid", "html-xml-lang-mismatch"],
    customRule: "lang-attr",
    description: "주로 사용하는 언어를 명시해야 한다.",
  },
  {
    id: "7.2.1",
    name: "사용자 요구에 따른 실행",
    nameEn: "On input",
    principle: 3,
    principleName: "이해의 용이성",
    level: "A",
    auto: "partial",
    axeRules: [],
    customRule: "on-input",
    description: "사용자가 의도하지 않은 기능은 실행되지 않아야 한다.",
  },
  {
    id: "7.2.2",
    name: "찾기 쉬운 도움 정보",
    nameEn: "Consistent help",
    principle: 3,
    principleName: "이해의 용이성",
    level: "A",
    auto: "partial",
    axeRules: [],
    customRule: "consistent-help",
    description: "도움 정보가 제공되는 경우, 각 페이지에서 동일한 상대적 순서로 접근할 수 있어야 한다.",
  },
  {
    id: "7.3.1",
    name: "오류 정정",
    nameEn: "Error identification",
    principle: 3,
    principleName: "이해의 용이성",
    level: "A",
    auto: "partial",
    axeRules: ["aria-allowed-attr", "aria-valid-attr-value"],
    description: "입력 오류를 정정할 수 있는 방법을 제공해야 한다.",
  },
  {
    id: "7.3.2",
    name: "레이블 제공",
    nameEn: "Labels provided",
    principle: 3,
    principleName: "이해의 용이성",
    level: "A",
    auto: true,
    axeRules: [
      "label",
      "select-name",
      "input-button-name",
      "aria-input-field-name",
    ],
    description: "사용자 입력에는 대응하는 레이블을 제공해야 한다.",
  },
  {
    id: "7.3.3",
    name: "접근 가능한 인증",
    nameEn: "Accessible authentication",
    principle: 3,
    principleName: "이해의 용이성",
    level: "AA",
    auto: "partial",
    axeRules: [],
    customRule: "accessible-auth",
    description: "인증 과정은 인지 기능 테스트에만 의존해서는 안 된다.",
  },
  {
    id: "7.3.4",
    name: "반복 입력 정보",
    nameEn: "Redundant entry",
    principle: 3,
    principleName: "이해의 용이성",
    level: "A",
    auto: false,
    axeRules: [],
    description: "이전 단계에서 입력한 정보가 자동으로 입력되거나 선택할 수 있어야 한다.",
  },

  // Principle 4: Robust
  {
    id: "8.1.1",
    name: "마크업 오류 방지",
    nameEn: "Parsing",
    principle: 4,
    principleName: "견고성",
    level: "A",
    auto: true,
    axeRules: ["duplicate-id", "duplicate-id-active", "duplicate-id-aria"],
    customRule: "markup-validity",
    description: "마크업 언어의 요소는 열고 닫음, 중첩 관계 및 속성 선언에 오류가 없어야 한다.",
  },
  {
    id: "8.2.1",
    name: "웹 애플리케이션 접근성 준수",
    nameEn: "Web application accessibility",
    principle: 4,
    principleName: "견고성",
    level: "A",
    auto: true,
    axeRules: [
      "aria-allowed-role",
      "aria-hidden-body",
      "aria-hidden-focus",
      "aria-required-attr",
      "aria-required-children",
      "aria-required-parent",
      "aria-roles",
      "aria-valid-attr",
      "aria-valid-attr-value",
    ],
    description: "콘텐츠에 포함된 웹 애플리케이션은 접근성이 있어야 한다.",
  },
];

export function getKwcagById(id: string): KwcagItem | undefined {
  return KWCAG_ITEMS.find((item) => item.id === id);
}

export function getKwcagByPrinciple(principle: number): readonly KwcagItem[] {
  return KWCAG_ITEMS.filter((item) => item.principle === principle);
}

export function getKwcagByAxeRule(axeRuleId: string): KwcagItem | undefined {
  return KWCAG_ITEMS.find((item) => item.axeRules.includes(axeRuleId));
}

export function getAllAxeRuleIds(): readonly string[] {
  const ids = new Set<string>();
  for (const item of KWCAG_ITEMS) {
    for (const ruleId of item.axeRules) {
      ids.add(ruleId);
    }
  }
  return [...ids];
}

export const PRINCIPLE_NAMES: Record<number, string> = {
  1: "인식의 용이성",
  2: "운용의 용이성",
  3: "이해의 용이성",
  4: "견고성",
};

export const PRINCIPLE_ITEM_COUNTS: Record<number, number> = {
  1: 9,
  2: 15,
  3: 7,
  4: 2,
};
